### ISSUE TITLE
The star count trend seems wrong

### ISSUE THREAD

**Issue by boxed** [danihodovic/django.wtf#249]
https://django.wtf/repo/iommirocks/iommi

It has been saying "100% more than last month" for several months now. That's not true.

https://django.wtf/repo/boxed/django-fastdev seems to also have the same issue

https://django.wtf/repo/Showmax/django-admin-page-lock looks suspicious too

**Comment by danihodovic** [comment]
Yep, something is off here...

**Comment by danihodovic** [comment]
For some reason iommi stopped indexing between February and June

![image](https://github.com/danihodovic/django.wtf/assets/5557301/363e026d-5e7b-41fd-a60d-497c245af493)

**Comment by danihodovic** [comment]
Can you add "django" as a Github topic to your repositories?

**Comment by danihodovic** [comment]
Showmax/django-admin-page-lock doesn't have topics either and is archived.

**Comment by boxed** [comment]
Aha, I didn't know about that. Thanks! I have added it to django-fastdev and iommi.

Is that why the indexing is weird or is that a separate thing?

**Comment by danihodovic** [comment]
> Is that why the indexing is weird or is that a separate thing?

I think so. Technically it should index the repo if it has a topic with "django" or if the keyword "django" exists in the README. The latter doesn't seem to work and I'm not sure why...

https://github.com/danihodovic/django.wtf/blob/master/django_wtf/core/github_api_urls.py#L15-L22

**Comment by boxed** [comment]
This looked good on the site now!
