### ISSUE TITLE
Trending page accuracy?

### ISSUE THREAD

**Issue by boxed** [danihodovic/django.wtf#251]
I might be stupid and doing the math wrong, but I have problems getting the 14 day trend data to make sense.

For iommi there are these added stargazers added the last 14 days:
```
2024-06-19 22:29:16+00:00 danialkeimasi
2024-06-20 07:57:49+00:00 HamadTheIronside
2024-06-20 09:39:53+00:00 BartKaminski
2024-06-20 10:32:48+00:00 bk
2024-06-20 13:49:31+00:00 mrdotss
2024-06-22 13:33:15+00:00 pyaehein
2024-06-22 18:29:47+00:00 a-atalla
2024-06-25 04:30:20+00:00 didorothy
2024-06-28 16:58:50+00:00 coolmian
```

I count that as 9. So 14 days ago iommi probably had ~653-9=644 stars (assuming no deleted stars.. should be close enough I think). That should be an increase of 1.3%. 

1.3% increase should mean iommi should be visible on page 2: https://django.wtf/trending/?page=2 but it's not.

**Comment by danihodovic** [comment]
You will probably have to wait a month for the repo to have past history. Indexing is not done retroactively.

**Comment by boxed** [comment]
Ah. But after 14 days this should at least show reasonable numbers for this specific page right? 14 days from when django.wtf started correctly indexing, which would be like yesterday?

**Comment by boxed** [comment]
Got it. Thanks.
