### ISSUE TITLE
Something fishy about #1 trending package today

### ISSUE THREAD

**Issue by boxed** [danihodovic/django.wtf#255]
[muhammad-fiaz/portfolio](https://django.wtf/repo/muhammad-fiaz/portfolio) is the top trending package today, but it's not django or even python as far as I can tell.

**Comment by adinhodovic** [comment]
Think the whole backend is django.

https://github.com/muhammad-fiaz/portfolio/tree/main/backend/portfolio

And it mostly comes from the github tag "django"

**Comment by boxed** [comment]
Aha. My bad. Seemed not relevant to django.wtf when I looked at it. 🤷

**Comment by danihodovic** [comment]
Bra att du håller koll
